version: "3.9"
services:
  db:
    image: postgres:15.1-alpine
    ports:
      - "2345:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=bewise_1

  app:
    build: .
    container_name: bewise-1
    command: bash -c "uvicorn main:app --host 0.0.0.0"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:mypassword@db/bewise_1
    depends_on:
      db:
        condition: service_healthy
